// Command src is the WASI demo handler for testsites/wasi: an ordinary Go
// program that reads a MelCGI request on stdin and prints an HTML page.
//
//	GOOS=wasip1 GOARCH=wasm go build -o testsites/wasi/hello.html.wasi ./testsites/wasi/src
package main

import (
	"bufio"
	"crypto/rand"
	"fmt"
	"html"
	"io"
	"os"
	"sort"
	"strings"
	"time"
)

func main() {
	handle(os.Stdin, os.Stdout, time.Now())
}

// handle reads a MelCGI request from r and writes the HTML response to w.
func handle(r io.Reader, w io.Writer, now time.Time) {
	vars := map[string]string{}
	in := bufio.NewReader(r)
	for {
		line, err := in.ReadString('\n')
		line = strings.TrimSuffix(line, "\n")
		if line == "" || err != nil {
			break
		}
		k, v, _ := strings.Cut(line, "=")
		vars[k] = v
	}
	body, _ := io.ReadAll(io.LimitReader(in, 4096))
	names := make([]string, 0, len(vars))
	for k := range vars {
		names = append(names, k)
	}
	sort.Strings(names)
	var nonce [6]byte
	rand.Read(nonce[:])

	fmt.Fprint(w, "Content-Type: text/html; charset=utf-8\n\n")
	fmt.Fprintln(w, `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Hello from WASI</title>`)
	fmt.Fprintln(w, `<style>body{font:16px/1.5 system-ui,sans-serif;max-width:44rem;margin:2rem auto;padding:0 1rem}td{padding:.15rem .6rem;font-family:ui-monospace,monospace}</style></head><body>`)
	fmt.Fprintln(w, `<h1>Hello from WASI</h1>`)
	fmt.Fprintln(w, `<p>This page was generated by a Go program compiled to WebAssembly, running inside melhttpd's sandbox (no files, no network) through MelCGI.</p>`)
	fmt.Fprintf(w, "<p>Server time: %s · random: %x</p>\n", now.UTC().Format(time.RFC3339), nonce)
	fmt.Fprintln(w, `<h2>Your request</h2><table>`)
	for _, k := range names {
		fmt.Fprintf(w, "<tr><td>%s</td><td>%s</td></tr>\n", html.EscapeString(k), html.EscapeString(vars[k]))
	}
	fmt.Fprintln(w, `</table>`)
	if len(body) > 0 {
		fmt.Fprintf(w, "<h2>Body</h2><pre>%s</pre>\n", html.EscapeString(string(body)))
	}
	fmt.Fprintln(w, `<form method="post"><input name="message" value="hello, sandbox"> <button>POST</button></form></body></html>`)
}
